### PR TITLE
Lexer Finished

### PR DESCRIPTION
**Pull request by VinaLx**
Lexical analyser is finished.
- Most analysis are done with the help of `lexer::detail::LookAheadStream`.
- Interpolation e.g.`"say: ${"hello" + "world"}"` is done by maintaining a `Context`(`sushi::lexer::Context`) stack, and coordination of different contexts will be done by the efforts of both lexer (`sushi::lexer::Lexer`) and parser. (not implemented yet)
- Other analyses are mostly done in `sushi/lexer/lexeme.cpp`

todo:
- Modify language specification to fit the implementation.
- Improve the arrangement and completeness of test cases.
- Refine CMakeLists
- maintain & debug.

### CODE REVIEW

**Comment by jskyzero** [comment]
1. I must say sorry for I don't review these code in detail.
2. cnanfile.txt requires update?
    so the the only gtest I can find in the conan-center is gtest:bincrafters, maybe it should update to `gtest/1.8.0@bincrafters/stable`
3. Linking CXX executable bin/lexer-test error, the error message is bellow
```
...
[100%] Linking CXX executable bin/lexer-test
CMakeFiles/lexer-test.dir/test/lexer/error-handling.cpp.o: In function `testing::AssertionResult::AppendMessage(testing::Message const&)':
error-handling.cpp:(.text._ZN7testing15AssertionResult13AppendMessageERKNS_7MessageE[_ZN7testing15AssertionResult13AppendMessageERKNS_7MessageE]+0x86): undefined reference to `testing::Message::GetString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
CMakeFiles/lexer-test.dir/build.make:224: recipe for target 'bin/lexer-test' failed
make[2]: *** [bin/lexer-test] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/lexer-test.dir/all' failed
make[1]: *** [CMakeFiles/lexer-test.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
4. Thanks for your outstanding work and sorry for my absence.

**Comment by VinaLx** [comment]
Current recipe for gtest works well for me. Did conan fail to find that package for you? 
And the linking error doesn’t look like an error anywhere in my code though.

I’ll check the gtest recipe later.

**Comment by jskyzero** [comment]
Yes, it fails to find gtest, so I have to find which works for me and I update that line as I said before ( conan fails to find on my Ubuntu 16.04 and 18.04

**Comment by DaddyTrap** [comment]
Totally same issue as @jskyzero mentioned above for me. Using Ubuntu 18.04.
...Is there no error on Mac even if reinstall the conan packages?

I'm trying to find out how to fix it on Ubuntu.

**Comment by VinaLx** [comment]
@jskyzero @DaddyTrap add another conan remote repository
```sh
conan remote add lasote https://api.bintray.com/conan/lasote/conan-repo
```
Is this repository that contains the [`gtest:conan`](https://bintray.com/lasote/conan-repo/gtest%3Aconan).

**Comment by DaddyTrap** [comment]
@VinaLx It **WORKS** with something extra. Here's what I've done.

```bash
cd bulid
conan remote add lasote https://api.bintray.com/conan/lasote/conan-repo
conan install .. -s compiler=gcc -s compiler.libcxx=libstdc++11 --build gtest
```

Then, with gtest built from source, build the project.

```bash
cmake ..
make
```
---
However, there is one test failed on my Ubuntu. I'm not sure if it is my solution cause this.

```bash
username@machine:~/path/to/sushiscript/build$ ./bin/lexer-test
Running main() from gmock_main.cc
[==========] Running 21 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 5 tests from ErrorHandling
[ RUN      ] ErrorHandling.TestUnknownChar
[       OK ] ErrorHandling.TestUnknownChar (0 ms)
[ RUN      ] ErrorHandling.TestUnclosedString
[       OK ] ErrorHandling.TestUnclosedString (0 ms)
[ RUN      ] ErrorHandling.TestUnclosedChar
[       OK ] ErrorHandling.TestUnclosedChar (0 ms)
[ RUN      ] ErrorHandling.TestInvalidChar
[       OK ] ErrorHandling.TestInvalidChar (0 ms)
[ RUN      ] ErrorHandling.TestExpectSlash
[       OK ] ErrorHandling.TestExpectSlash (0 ms)
[----------] 5 tests from ErrorHandling (0 ms total)

[----------] 6 tests from InterpolationTest
[ RUN      ] InterpolationTest.TestStringLiteral
[       OK ] InterpolationTest.TestStringLiteral (0 ms)
[ RUN      ] InterpolationTest.TestString
[       OK ] InterpolationTest.TestString (0 ms)
[ RUN      ] InterpolationTest.TestRawToken
[       OK ] InterpolationTest.TestRawToken (0 ms)
[ RUN      ] InterpolationTest.TestRaw
[       OK ] InterpolationTest.TestRaw (0 ms)
[ RUN      ] InterpolationTest.TestPathLiteral
[       OK ] InterpolationTest.TestPathLiteral (0 ms)
[ RUN      ] InterpolationTest.TestPath
[       OK ] InterpolationTest.TestPath (1 ms)
[----------] 6 tests from InterpolationTest (2 ms total)

[----------] 5 tests from SimpleSequence
[ RUN      ] SimpleSequence.TestLineBreak
[       OK ] SimpleSequence.TestLineBreak (0 ms)
[ RUN      ] SimpleSequence.TestComment
[       OK ] SimpleSequence.TestComment (0 ms)
[ RUN      ] SimpleSequence.TestWhitespaces
[       OK ] SimpleSequence.TestWhitespaces (0 ms)
[ RUN      ] SimpleSequence.TestLocation
/home/daddytrap/Work/sushiscript/test/lexer/./util.h:70: Failure
AllEqual<Strong>(test, expected) evaluates to false, where
test evaluates to [`RawStr, 0, (1, 1)`, `Segment, $IDENT, (1, 1)`, `InterDone, 0, (1, 7)`, `RawStr, 0, (1, 9)`, `InterStart, 0, (1, 9)`]
expected evaluates to [`RawStr, 0, (1, 1)`, `Segment, IDENT, (1, 1)`, `InterDone, 0, (1, 6)`, `InterStart, 0, (1, 9)`]
Google Test trace:
/home/daddytrap/Work/sushiscript/test/lexer/./util.h:67: $IDENT  ${
[  FAILED  ] SimpleSequence.TestLocation (0 ms)
[ RUN      ] SimpleSequence.TestConnected
[       OK ] SimpleSequence.TestConnected (1 ms)
[----------] 5 tests from SimpleSequence (1 ms total)

[----------] 5 tests from SingleTokenTest
[ RUN      ] SingleTokenTest.TestIdentifier
[       OK ] SingleTokenTest.TestIdentifier (0 ms)
[ RUN      ] SingleTokenTest.TestInteger
[       OK ] SingleTokenTest.TestInteger (0 ms)
[ RUN      ] SingleTokenTest.TestPunctuation
[       OK ] SingleTokenTest.TestPunctuation (0 ms)
[ RUN      ] SingleTokenTest.TestKeywords
[       OK ] SingleTokenTest.TestKeywords (0 ms)
[ RUN      ] SingleTokenTest.TestCharLiteral
[       OK ] SingleTokenTest.TestCharLiteral (1 ms)
[----------] 5 tests from SingleTokenTest (1 ms total)

[----------] Global test environment tear-down
[==========] 21 tests from 4 test cases ran. (5 ms total)
[  PASSED  ] 20 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SimpleSequence.TestLocation

 1 FAILED TEST
```

**Comment by VinaLx** [comment]
Err, conan often requires extra configuration to accomplish something.
And the fail test was my fault, forgot to update test cases along with the refactored code. Fixed in the commit above.

**Pull request merged**
